version: '3.1'
services:
  app:
    container_name: animals-postgres
    image: animals-postgres
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=springbootdb